### ISSUE TITLE
LZ4 Doesn't Support Partial Decode of SOLID Block, Leading to Failure

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.Archives.Nx#16]
LZ4 Variant of this issue/fix https://github.com/Nexus-Mods/NexusMods.Archives.Nx/pull/13.
Originally reported as https://github.com/Nexus-Mods/NexusMods.Archives.Nx/issues/9 for ZStd.

***I forgot this issue existed***. Despite adding the missing API in the underlying library as https://github.com/MiloszKrajewski/K4os.Compression.LZ4/pull/90 , I forgot to apply it to this library, after my changes were merged.

This is a very trivial fix, so I'm getting this done out of the way so it doesn't bite end users (us included) in the back later.

**Comment by erri120** [comment]
Done in #17.
